language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-android-starter' ]; then cd .. && eval "mv $currentfolder generator-android-starter" && cd generator-android-starter; fi
